### ISSUE TITLE
group_spacing attribute in TreeDiagram

### ISSUE THREAD

**Issue by FourierMourier** [MerrimanInd/drawpyo#43]
Hi. Can you please describe what the `group_spacing` attribute in the `drawpyo.diagram_types.tree.TreeDiagram` class is intended to do? Because, for now, there's no keyword description or any usages.

**Comment by MerrimanInd** [comment]
It's not in the documentation because it was never implemented so the kwarg code is dead. But it was going to allow fine tuning of the spacing between groups of items. Currently the spacing is the same between items within a group and between adjacent groups. It may get implemented someday but because of the recursion in the TreeDiagram layout functions, laying out items in a group is the same code as laying out the groups, and all the way on up.
